ALTER TABLE "products"
  ADD COLUMN "lot_quantity" INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN "production_cost_total" DOUBLE PRECISION NOT NULL DEFAULT 0,
  ADD COLUMN "packaging_cost_total" DOUBLE PRECISION NOT NULL DEFAULT 0,
  ADD COLUMN "labels_cost_total" DOUBLE PRECISION NOT NULL DEFAULT 0,
  ADD COLUMN "shipping_materials_cost_total" DOUBLE PRECISION NOT NULL DEFAULT 0,
  ADD COLUMN "factory_freight_cost_total" DOUBLE PRECISION NOT NULL DEFAULT 0,
  ADD COLUMN "payment_fee_percent" DOUBLE PRECISION NOT NULL DEFAULT 0,
  ADD COLUMN "sales_tax_percent" DOUBLE PRECISION NOT NULL DEFAULT 0,
  ADD COLUMN "company_shipping_cost_avg" DOUBLE PRECISION NOT NULL DEFAULT 0,
  ADD COLUMN "customer_acquisition_cost_avg" DOUBLE PRECISION NOT NULL DEFAULT 0,
  ADD COLUMN "desired_profit_margin_percent" DOUBLE PRECISION NOT NULL DEFAULT 0;
